name: Twitter Live Sports Bot

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  tweet_goals:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # রিপোজিটরিতে ফাইল সেভ করার পারমিশন

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests tweepy cloudscraper


      - name: Run Bot Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python bot.py

      - name: Commit tracked goals
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          touch tweeted_goals.txt # ফাইল না থাকলে এরর এড়াতে ফাঁকা ফাইল বানাবে
          git add tweeted_goals.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Updated tweeted goals list" && git push)
